### ISSUE TITLE
Support ethereal nodes and ores

### ISSUE THREAD

**Issue by fwhcat** [joe7575/techpack#1]
It would be great if the machines, harvester and quarry,
would support [ethereal](https://github.com/tenplus1/ethereal) nodes & ores. (with an optional dependency of course).

I have a quarry but it doesn't get the bakedclay for example.
My Harvester doesn't care about onions :)
etc.

Thanks for this awesome mod.

**Comment by joe7575** [comment]
I will give it a try, perhaps next weekend

**Comment by joe7575** [comment]
Support for Ethereal added
