### ISSUE TITLE
TechPack on 5.4.1 Server Doesn't Display Recipe for Gravel Sieve, An Overlooked Modding Error?

### ISSUE THREAD

**Issue by FriendlyGamer** [joe7575/techpack#102]
Could you please advise us if it was meant to not be displayed on the sfinv's Crafting Guide? 

We ended up having to find it online and I am not sure if that was supposed to happen since new players might not know this. 

Thanks very much in advance for your help!

**Comment by joe7575** [comment]
I have no idea how to do that. 
I recommend to use the mod `unified_inventory`. That has an interface function to register foreign recipes. 
AFAIK `sfinv` does not provide something similar.

**Comment by BuckarooBanzay** [comment]
This looks like a bug in the `sfinv` mod, the recipe is properly registered:
https://github.com/joe7575/techpack/blob/7f7c568a08d1931d04e939f6f052a159c79f5fe6/gravelsieve/init.lua#L704-L710

**Comment by FriendlyGamer** [comment]
> This looks like a bug in the `sfinv` mod, the recipe is properly registered:
> https://github.com/joe7575/techpack/blob/7f7c568a08d1931d04e939f6f052a159c79f5fe6/gravelsieve/init.lua#L704-L710

Then how come everything elses in this mod pack get registered into the guide? We can see among other things... 
Tubes 
Grinder
Pushers (both variants) 
Distributors 
Techpack Street Lamp (or whatever it was) 
and so on... 

How come the Gravel Sieve is the "single man out"?
