### ISSUE TITLE
Papyrus is always considered as oven fuel

### ISSUE THREAD

**Issue by superfloh247** [joe7575/techpack#106]
Hi,

I'm trying to build an automated bakery, and therefore I need to cook papyrus ti sugar.
But the tubelib distributor does not put papyrus in the upper oven box, papyrus is always considered as fuel und get put in the lower box, even if there is already coal in the oven as fuel.

I don't have an easy solution. One idea is to put papyrus is the upper box if there is already another fuel in the lower box, but this will break when the lower box is empty.
Another idea is to make delivery to ovens depending on the side where the tube is connected to the oven. This will break lots of existing installations.

Yet another idea: new node: switcher. Placed next or on top of an oven, it delivers items either to the upper or lower oven box. Configured similar to distributors.

Or did I miss anything? Is there already a way to cook papyrus?

Greetings,
Florian

**Comment by joe7575** [comment]
I changed the code. If you put papyrus in the top box and then start the pusher to push papyrus, the furnace will save that item as "no fuel". Alternatively, this should also work with other items.

**Comment by superfloh247** [comment]
Hi, does not work as intended. When the ingredient pusher is empty, but the fuel pusher still has something to push, then coal gets added as fuel and ingredient.

![Bildschirmfoto 2021-09-22 um 10 54 08](https://user-images.githubusercontent.com/26180993/134313692-b897dff4-0e50-4506-aa73-736f04fe0723.png)

**Comment by 0siribix** [comment]
From my tests, this should only happen if you put coal in the top once for that furnace and you should be able to reset it by digging the furnace and placing a new one. Did that not work?

**Comment by superfloh247** [comment]
Hmm, maybe it's my fault.
I rearranged my furnaces now. Ingredient tubes now connect to the top, fuel tubes to the side. This works very well for all kinds of ingredients and fuels.
