### ISSUE TITLE
HP pusher back texture is rotated 180 twice resulting in the texture being reverse

### ISSUE THREAD

**Issue by 0siribix** [joe7575/techpack#110]
/tubelib_addons3/pusher.lua

Line 80
"tubelib_pusher1.png^[transformR180]^tubelib_addons3_node_frame4.png^[transformR180]",

should be

"tubelib_pusher1.png^tubelib_addons3_node_frame4.png^[transformR180]",

How to reproduce.
Place a HP pusher and move to the back where "IN" is facing to the right. This texture is reverse.

**Comment by joe7575** [comment]
Thanks, fixed
