### ISSUE TITLE
Can't get tubelib to put fuel into lwcomponents forcefield generator

### ISSUE THREAD

**Issue by AmyMoriyama** [joe7575/techpack#114]
Not sure who to "report" this to, but seems I would go with tubelib which is part of this pack. Can't put fuel into lwcomponents forcefield generator.

**Comment by joe7575** [comment]
> Can't put fuel into lwcomponents forcefield generator.

- Put "by hand" or put "by tube/pusher"?
- What kind of fuel? tubelib bio fuel?

**Comment by AmyMoriyama** [comment]
Made another issue requesting compatibility with the lwcomponents mod
