### ISSUE TITLE
Transparency issues on 5.9 client / 5.7 server

### ISSUE THREAD

**Issue by MLK94** [joe7575/techpack#128]
My apologies if this isn't the right place, this is my first time reporting an issue! 

Been seeing transparency issues using 5.9 client on my 5.7 server, gravelsieve in this case is solid black underneath. 

![screenshot_20240906_201158](https://github.com/user-attachments/assets/686af354-5c54-4bc5-8c92-b5313612cd32)

Will an update fix this? I don't think I have updated techpack for a while.

**Comment by MLK94** [comment]
Ah, I found the issue. I added 'use_texture_alpha="clip"' inside each of the 4 minetest.registered_node routines and rebooted. I did not check to see if an updated version of techpack had these fixes.

**Comment by joe7575** [comment]
This is already fixed: https://github.com/joe7575/techpack/commit/4bd27c544adcf5565d5e1b9fb316172e0c2d7c44

![screenshot_20240908_174238](https://github.com/user-attachments/assets/232b5eff-5a07-45c4-95cc-ec41ef430311)
