### ISSUE TITLE
compatability w/ moretrees (and other mods)

### ISSUE THREAD

**Issue by obl3pplifp** [joe7575/techpack#15]
(note: how do i mark this as an enhancement?)

I've written a compatability mod to include nodes from moretrees, as well as some crops from farming that aren't harvested for no reason i can understand. 

https://github.com/obl3pplifp/techpack_compat

I can re-submit this as a PR if that is more helpful, but i figured I'd let you decide how to integrate it into techpack.

**Comment by joe7575** [comment]
Thanks, I will take over your code.

**Comment by joe7575** [comment]
Code is added, thanks again.
