### ISSUE TITLE
compatability: mesecons movement nodes

### ISSUE THREAD

**Issue by obl3pplifp** [joe7575/techpack#16]
(feature request)

Probably because of the metadata that they include, most tubelib nodes do not behave well when they are moved using mesecons pistons or movestones. Fixing mesecons to do something sane seems intractable; the easier solution is to prevent them from being moved in the first place.

For an example of how to prevent nodes from being moved by mesecons, see 

https://github.com/obl3pplifp/bad_piston_no_biscuit

This could possibly be re-submitted as a PR if desired.

**Comment by joe7575** [comment]
Will be added, thanks

**Comment by joe7575** [comment]
see #5
