### ISSUE TITLE
compatability: worldedit

### ISSUE THREAD

**Issue by obl3pplifp** [joe7575/techpack#18]
(feature request)

The worldedit does not work well with techpack blocks (mostly tubelib). For instance, tubelib machines that are placed with this tool recieve *THE SAME* WLAN ID. I don't know what a solution to this problem looks like; it may have to be fixed on worldedit's side.

**Comment by joe7575** [comment]
Right, I know that problem and had already asked for a solution in the worldedit thread.
Unfortunately with no answer.

**Comment by joe7575** [comment]
see #5
