### ISSUE TITLE
Play on BlS

### ISSUE THREAD

**Issue by obl3pplifp** [joe7575/techpack#19]
I'm inviting you to play on Blocky Survival. We're one of the biggest public minetest servers, and we use techpack heavily. Billy-S, who's submitted issues to you before, is the admin. If you check in semi-regularly, we'd love to show you our numerous weird tubelib issues. We have work-arounds for many of them, but I thought I'd extend an offer for you to check it out firsthand.

**Comment by joe7575** [comment]
I know the server. It is great. I have already played there. But I am not a player, I am more the mod programmer. Blocky Survival is not using the latest version of techpack (AFAIK) and its probably modified. I guess, some of the issues should already be fixed with the latest version.

**Comment by obl3pplifp** [comment]
Alright. Just thought I'd offer :) We don't always have the most recent version, but we do update every so often (which often results in lots of weird behaviour itself). I don't think we've done any major modification to the mod itself though.
Closing this.
