### ISSUE TITLE
Oversized stacks when removing items from warehouses

### ISSUE THREAD

**Issue by obl3pplifp** [joe7575/techpack#21]
Hello again,
It's possible for players to use warehouses to create oversized stacks.

Steps to reproduce:
1. Place a warehouse
2. Get several stacks of a stackable item
3. Put set a filter and put multiple (3 or more) stacks into it
4. Drag the contents of the factory onto an arbitrary item in your inventory that's different than what's in the factory

You'll end up w/ a stack in your inventory that's much larger than it should be (though it seems to be one stack less than what the machine contained). The other item disappears.

Tested using current tubelib (master branch, checked out today) with minetest 0.4.17, on linux.

**Comment by joe7575** [comment]
Thanks for the report. It seams to be an open issue: https://github.com/minetest/minetest/issues/6534
But I will try to find a workaround.

**Comment by joe7575** [comment]
I've uploaded v2.03.01 which fixes the issue
