### ISSUE TITLE
HighPerf pusher no longer pulls stacks from the harvester

### ISSUE THREAD

**Issue by obl3pplifp** [joe7575/techpack#22]
It used to pull full stacks, and is still documented as doing so, but it currently doesn't. Looks like this is because the harvester doesn't implement 'on_pull_stack'. I'm not sure if this is intentional or not. If it's an oversight, it's a trivial fix.

**Comment by joe7575** [comment]
Right, code and documentation does not match. It could easily be added but the harvester can't pick such amount of items that the HighPerf pusher would be needed, or?

**Comment by obl3pplifp** [comment]
The harvester can pull up to 18 nodes every 4 seconds when farming tall trees, and positioned at the same level as the base of the tree. While 5 fast pushers can keep the machine from clogging in such a setup, that's much more expensive and space-intensive. 4 fash pushers have been enough in any practical tree farm I've built, which, while slightly more reasonable, isn't ideal - I usually have them all piped into a single HP chest, and an HP pusher moving things from there to an HP distributor to separate the wood, the leaves, and anything else.

I leave it to you to decice whether this is a reasonable solution, though.

**Comment by joe7575** [comment]
fixed with v2.03.02
