### ISSUE TITLE
Support pulling stacks from some other machines

### ISSUE THREAD

**Issue by obl3pplifp** [joe7575/techpack#23]
This is a feature request, or at least, request for the idea to be considered, as opposed to the bug report in #22 . It'd be nice if some of the other machines allowed on_pull_stack, particularly the autocrafter, grinder, and HighPerf pushing chest, but those never supported it in the past, and you might consider such a capability to be unbalanced.

**Comment by joe7575** [comment]
I could add it. Are you using v2 now or will you backport the changes?

**Comment by obl3pplifp** [comment]
Using v2.

I suggest those machines in particular because they can all fill up their "output inventory" faster than three fast pushers can handle.

**Comment by joe7575** [comment]
fixed with v2.03.02
