### ISSUE TITLE
Black Holes do not display correct "items disappeared" counts when being fed by HighPerf machines.

### ISSUE THREAD

**Issue by obl3pplifp** [joe7575/techpack#24]
When being fed by a HighPerf machine, a black hole displays the number of times a stack/partial stack was disappeared, not the number of "items".

This is, admittedly, a low-priority issue. The only time that number matters to me is when I'm testing the efficacy of various setups in a single-player world.

**Comment by joe7575** [comment]
fixed with v2.03.02
