### ISSUE TITLE
HighPerf distributors don't function without an active filtered channel.

### ISSUE THREAD

**Issue by obl3pplifp** [joe7575/techpack#25]
A HighPerf distributor with one or more active unfiltered channels, but no active filtered channels, will never output anything. This is in contrast to a regular distributor, which will round-robin between available active unfiltered channels in such a situation. 

My current work-around in such a situation is to set up a "dummy" filtered channel in the HighPerf distributor, making use of some item that will absolutely never enter the distributor. However, this has the downside of leaving only 3 usable channels.

**Comment by joe7575** [comment]
fixed with v2.03.02
