### ISSUE TITLE
Unstackable items vanish when using HighPerf pushers

### ISSUE THREAD

**Issue by obl3pplifp** [joe7575/techpack#29]
This is a fairly old issue, at least 3 or 4 months, but I forgot about it.

If you move unstackable items between two HP chests using a HP pusher, most of them will disappear. 

e.g. put 32 diamond picks in one chest, and push them into another. I only end up with 2 picks. This also works w/ buckets of water, terumet machines, and some other stuff.

**Comment by joe7575** [comment]
Thanks  obl3pplifp,
This was indeed a huge bug. Strange that it has never been discovered.
