### ISSUE TITLE
Issue w/ teleporters after upgrade

### ISSUE THREAD

**Issue by fluxionary** [joe7575/techpack#32]
When Blocky Survival first updated to techpack 2.? from 1.?, around March 23rd, players started having issues with teleporters, and this problem has never been resolved. The issue is that the destination teleporter, instead of putting items into the destination machine, just dumps the item onto the floor. This happens even if one or both teleporters are removed, or even replaced with new teleporters. Personally I've just stopped using teleporters. However, everyone else reports that newly setup systems with teleporters work just fine.

I've never dug too deeply into why this issue is happening, or what a resolution looks like. As I can't supply any detailed information at this time, this issue is more of an FYI, in case you have any ideas, being more familiar with the mod.

**Comment by joe7575** [comment]
The conversion of the teleporters from v1 to v2 was tricky.  Teleporters in v1 were implemented as nodes in 'tubelib_addons3' had their own pairing logic and worked as "application nodes" on top of tubelib. In v2, I implemented the teleporter logic as part of the tubelib2 lib. Unfortunately it was not possible to convert the teleporter data under all circumstances. But replacing both and adding both nodes again should always work.
