### ISSUE TITLE
Overzealous replacement by defect dummies

### ISSUE THREAD

**Issue by obl3pplifp** [joe7575/techpack#33]
Since the introduction of defect dummies as a solution to cloned/moved tubelib machines, many players on Blocky Surival have reported that their entire factories, or a few machines in their factories, have mysteriously turned into defect dummies. I know for a fact that many of these machines were not placed w/ a node replacement tool or worldedit, or moved with a piston, and that many of these machines had valid ID numbers beforehand. I'm not entirely sure what is going on. For the moment, I have just disabled the code that turns machines into dummies, which is a stopgap until I find the the time to investigate this further. 

As I don't have any detailed information at the moment, this Issue is mostly an FYI.

**Comment by joe7575** [comment]
I can not confirm that. On my own server, there are also huge machines which seem to work fine.
Unfortunately most of the players are gone, so there is not so much activity anymore.

**Comment by obl3pplifp** [comment]
Sorry it's taken me a while to respond, I've been busy.
I've managed specifically discover that the machines possess a valid ID number, but lack "node info", e.g. `tubelib.get_node_info(number)` returns nil, but that's about it. 
For such a machine, would it be possible to re-initialize the node info instead of turning it into a defect dummy?

**Comment by joe7575** [comment]
Sorry, I am just back from vacation. I will check if this will work

**Comment by joe7575** [comment]
Having an ID number, but lacking "node info" is a clear indication for moved nodes.
Nevertheless, I have added the repair code for such kind of nodes.
