### ISSUE TITLE
High Perf Funnel?

### ISSUE THREAD

**Issue by andrenete** [joe7575/techpack#36]
It seems that you can throw a stack of blocks in a funnel but you can't pull a full stack from it even with High Perf Pusher.

Is it possible that you can add High Perf Funnel? Or maybe fix regular funnel behavior by allowing to pull full stacks from it with High Perf Pusher? I personally think it would be better to add a new block, as it fits well with other highperf stuff.

**Comment by andrenete** [comment]
#37

**Comment by joe7575** [comment]
pull request merged
