### ISSUE TITLE
IDs

### ISSUE THREAD

**Issue by piecubed** [joe7575/techpack#41]
Instead of storing everything in mod memory, and fetching based on IDs, why don't you just use the position of the node?  Then you can store it in the nodes meta, and even if you did it right, you wouldn't have to replace the node.  Your current system is rather inefficient, and is broken.

**Comment by joe7575** [comment]
Generate two test nodes where you cyclically increment a value by means of the node timer
A)  as meta variable:
  `meta:set_int("cnt", meta:get_int("cnt") + 1)`
and B) as memory variable:
  `mem.cnt = mem.cnt + 1`

Fill a map block with either the one or the other block and measure the server CPU load and network load and you will see the difference. B) is more that 10 times faster.

**Comment by piecubed** [comment]
However, this way, if you make your storage right, it wont corrupt.  You dont need to store tubelib information in mod memory, just store it in node metadata.

**Comment by piecubed** [comment]
And i mean by position.  Not by incremental IDs.

**Comment by piecubed** [comment]
Oh, i see what you are saying.  If there was a buffer that made the changes every 5 seconds or so, that would be fine.  Currently tubelib does it every 10 minutes, and it is always having data be corrupted in its storage.  Besides, tubelib is pretty inefficient anyways right now.

**Comment by joe7575** [comment]
What do you mean with corrupted? 
If you do no mistakes (moving machines around and things like that) the data will never be corrupted. The storage system behind tubelib has 3 stages:
- realtime data stored in RAM (mem) (as fast as it can be)
- this data in copied every 10 minutes to minetest storage (for the case the server crashes) and in addition when the server shuts down
- minetest will then store this mod storage into a file
see: https://rubenwardy.com/minetest_modding_book/en/map/storage.html#mod-storage

Again: What is corrupted? The machines or the mod storage data base?

**Comment by piecubed** [comment]
I haven't actually seen machines corrupting, but been talking with @fluxionary about it, and he knows.  IMO, you should use sql/postgresql natively for this.  Be much more reliable than mod storage.

**Comment by joe7575** [comment]
Yes, sql could be an option.
But it will not automatically help if you move nodes around. Therefore, you have to store the node related data based on an UUID and only this UUID is stored as node meta data.
Even using this aproach will not always help, e.g. if other node positions (relationships) are stored and you move/copy the nodes around.
The best option is to store as less as possible nonvolatile and use volatile memory (cache) for runtime data which can be recovered when necessary (after bootup / map load).
This should be the long term goal.

**Comment by andrenete** [comment]
Related question: Are unused IDs ever removed from the mod storage file? Or are they just softly "deallocated"?

It seems that uncontrolled storage growth can be a problem that leads to corruptions like broken buttons. This has happened to me many times on Blocky Survival, and it seems that some IDs were not even written to the file...

**Comment by fluxionary** [comment]
@andrenete the unused ID #s shouldn't be an issue, but there is an issue w/ metadata corruption that's never been resolved.

**Comment by joe7575** [comment]
For the mod there is no difference if 1,000, 10,000, or 100,000 IDs have to be maintained and stored, but I am afraid Minetest has its limitations in file size. What is the size of the file "mod_storage/tubelib" ?

**Comment by joe7575** [comment]
I optimized the database maintenance function to reduce the mod storage file size. On a test file I was able to reduce the file size to 15 percent. You should check and test this carefully before you use it on Blocky Survival.

Again some comments on your comments:

> You dont need to store tubelib information in mod memory, just store it in node metadata.

The Table "get position from number" has to be stored outside of nodes, you need a global lookup table for that. You can store the position in addition in any node. But this will not help if the global table is already corrupted.

> It seems that uncontrolled storage growth can be a problem that leads to corruptions like broken buttons. This has happened to me many times on Blocky Survival, server with hundreds of thousands of IDs, and it seems that some IDs were not even written to the file...

What is the current ID? What is the size of the file? Give me some figures

>  the unused ID #s shouldn't be an issue, but there is an issue w/ metadata corruption that's never been resolved.

The unused IDs increase the database file size which could probably be one reason for the issues. But in general there is no issue with the way the data is stored and maintained. 
IMO it makes no sense to switch to a real database format or trying other metadata models without knowing the root cause.

**Comment by joe7575** [comment]
Issue is solved or the opener doesn't seem to care anymore.
