### ISSUE TITLE
Liquid Sampler: Set Idle state instead of fault when there is no liquid

### ISSUE THREAD

**Issue by andrenete** [joe7575/techpack#44]
If there is no liquid in front of the sampler, its state switches to 'fault' and you need to reset it *manually*. Some mods are able to generate liquid sources *automatically* and for better compatibility with them I think it's better to set state to 'idle' when no liquid was found.

For example, [terumet](https://github.com/Terumoc/terumet) mod has a lava melter that generates lava sources. The process of generating is pretty slow and while you wait for lava, sampler goes to 'fault', so you can't grab the generated lava automatically.

Example of what I was trying to do:
![Screenshot_20200303_213820](https://user-images.githubusercontent.com/22382143/75807955-57a38300-5d97-11ea-84b6-63a259a2f875.png)

**Comment by joe7575** [comment]
Done
