### ISSUE TITLE
SaferLua tries to interpret "for" and ":" inside comments

### ISSUE THREAD

**Issue by Assargadon** [joe7575/techpack#48]
If I use "for" or ":" inside the comments, it throws errors:
- Invalid character ':'
and
- Invalid use of 'for'
correspondently. I don't know why these two, for example "if" keyword do not causes any problems.

Commenting still works, i.e. if my comment has no "for" and ":" substrings inside, everything works just fine.
Compiler do not tries to interpret or execute comments.

**Comment by joe7575** [comment]
Should be fixed now, give it a try...

**Comment by Assargadon** [comment]
Ok, thanks, I'll do it.
Never tried to install extensions manually yet, so it may take some time.
I don't think it's hard, I just never did it before :)
