### ISSUE TITLE
string.split returns Lua table, not SaferLua Array

### ISSUE THREAD

**Issue by Assargadon** [joe7575/techpack#49]
`string.split` is just Lua's imported function, and it returns table, not Array.

I was forced to use `Array(unpack(string.split(...)))` trick to get the "conventional" SaferLua's Array and be able, for example, to iterate over the splitted literals.

**Comment by Assargadon** [comment]
With just a little bit more efforts I was able to use this table to save _code_ to Server:

```
function hw()
    $print("Hello World")
end

tbl = string.split("", ":", false, -1)
tbl["HW"] = hw

tbl["__dump"] = function()
    res = string.split("", ":", false, -1)
    res.Type = "Store"
    res.Size = 10
    res.MemSize = 12
    res.Data = tbl
	    	return res
	end

$server_write(SRV, "tst", tbl);
pseudo_store = $server_read(SRV, "tst");
f = pseudo_store.get("HW")
f()
```

It prints "Hello World"

**Comment by joe7575** [comment]
Thanks for the report, I changed the function according to your proposal `Array(unpack(string.split(...)))`
