### ISSUE TITLE
Tubelib machine disappear after digging if player's inventory is full

### ISSUE THREAD

**Issue by Arigatas** [joe7575/techpack#50]
This happens for _some_ tubelib items but not for all. It applies i.e. for pusher, fast pusher, grinder, harvester.

Issue: If a player digs a grinder and his inventory is full, that item will be lost. The digged item won't drop onto the ground.

**Comment by Arigatas** [comment]
After some attempts I think I solved that bug. This bug happened due to the following circumstances: 
Some tubelib items have an aging effect, that means they're gonne be defect (with a certain probability) after processing a certain amount of items. If one digs an tubelib item this is taken into account by returning that tubelib item as defect depending from how heavily used it is so far.

This logic (= returning item as defect or non-defect?) was implemented in `NodeStates:after_dig_node() ` in `./tubelib/node_states.lua ` and used with the callback `after_dig_node()`. This callback is triggered _after_ the default behaviour of removing the node, dropping the item, etc. Therefore the default dropping of such items was made inactive and returning the item to the player's inventory was coded manually which lead to the buggy behaviour.

In my proposed solution the logic (returning the item defect or non-defect) is triggered _before_ the default behaviour for removing/dropping the node by replacing the `after_dig_node()` callback with the `on_dig()` callback

**Comment by fluxionary** [comment]
this issue is apparently happening on blocky survival; i'll attempt to replicate the issue and test the fix tomorrow.

**Comment by fluxionary** [comment]
see also https://github.com/BlockySurvival/issue-tracker/issues/89

**Comment by fluxionary** [comment]
created over a year ago. hooray for slow brain-death.

**Comment by fluxionary** [comment]
Fix seems to work on BlS
