### ISSUE TITLE
tubelib_addons2:doorblock works incorrectly

### ISSUE THREAD

**Issue by Jury-Me** [joe7575/techpack#55]
When you turn off the door block, it loses its rotation and texture, a video with this bug is available [here](https://youtu.be/6Y9D13nEk_s).

What could have caused this bug? I used the latest version of the techpack, I didn't use any other mods except tubelib2 and basic_materials.

(I apologize if I speak a little incorrectly, I use google translate.)

**Comment by joe7575** [comment]
Thanks for your report, I can reproduce the bug. Next weekend I will try to fix it

**Comment by joe7575** [comment]
Fixed
