### ISSUE TITLE
Warehouse voiding items when both pushing in and pulling out

### ISSUE THREAD

**Issue by oversword** [joe7575/techpack#61]
This one's a hard one, I have a fix but I'm sure it will need a lot of testing & some discussion about the best way to actually do it.

The primary issue is that the last two slots in the warehouse never seem to fill, this only occurs when you are pulling items out of the warehouse with a pusher - as well as presumably pushing them in to keep it replenished.

To replicate I recommend you set up:

Chest (High Perf) > Pusher (High Perf) > Warehouse > Pusher (High Perf) > Chest (normal)

The final chest (right most) should be full
Both pushers should be turned on until the right most one is blocked
The warehouse should be as full as possible
The first chest (left most) should be full and constantly fed with items (to fill up the warehouse)

Personally I crafted logs into planks into sticks to try and fill the warehouse as quickly as possible

The warehouse should be configured to accept this item only

Once the first 6 slots get full, the last two never manage to get above a few hundred, any further items pushed in simply disappear. 
This only happens when pulling items out into a full inventory.

Any further details are part of the solution, not the problem, so will be detailed in the PR.

**Comment by joe7575** [comment]
Fixed by  oversword. Thanks a lot!
