### ISSUE TITLE
Pushers can be used to send items into the invalid faces of a node

### ISSUE THREAD

**Issue by oversword** [joe7575/techpack#72]
Already solved, just writing this up

This is related to https://github.com/joe7575/tubelib2/issues/4
And also addresses issues related to teleporters described here https://github.com/joe7575/techpack/issues/67

Using the new feature that disallows tubes from connecting to teleporters, except for the front face with a hole in it, you can still create "spooky" connections by pushing items directly into the wrong side of the teleporter.

**Comment by joe7575** [comment]
Issue is fixed with #74 and #76. Many thanks to @oversword.
