### ISSUE TITLE
Major issue!!! tubelib.register_node is undefined on master

### ISSUE THREAD

**Issue by oversword** [joe7575/techpack#79]
While writing up #77 & #78 I pulled master to get the latest but it kept crashing the game without even starting, had to base those off of my last commit because I know it works.

Will look into this now, but no guarantees, idk how you borked it this bad

Actual error is:

```
ModError: Failed to load and run script from /home/cam/snap/minetest/1619/.minetest/mods/techpack/tubelib_addons2/init.lua:
...t/1619/.minetest/mods/techpack/tubelib_addons2/timer.lua:195: attempt to call field 'register_node' (a nil value)
stack traceback:
	...t/1619/.minetest/mods/techpack/tubelib_addons2/timer.lua:195: in main chunk
	[C]: in function 'dofile'
	...st/1619/.minetest/mods/techpack/tubelib_addons2/init.lua:19: in main chunk
Check debug.txt for details.
```

Tried commenting out that module, same error occurs in the next one loaded

**Comment by oversword** [comment]
I'm an idiot, this is because of version requirements. Shame I saw this error and not the version requirement error though, that might be worth fixing

**Comment by joe7575** [comment]
Thanks, I improved the version check, it was not visible to far.
