### ISSUE TITLE
Defective warehouses call `after_dig_node` which does not exist

### ISSUE THREAD

**Issue by oversword** [joe7575/techpack#92]
All the defect variant of the warehouses do this:
```
	after_dig_node = function(pos, oldnode, oldmetadata, digger)
		wh.after_dig_node(Box, pos, oldnode, oldmetadata, digger)
	end,
```

`wh.after_dig_node` does not exist, causing a crash of you dig this node, worth looking back in the code to try and figure out why this is here in the first place.

I will probably get to it soon if you don't

**Comment by joe7575** [comment]
the `wh.after_dig_node` is missing since #51 and should be replaced with a `wh.on_dig_node`
